ignore:
  - "TabBarUIActionUITests"
  - "TabBarUIActionDemo"
  - "Source/Previews/**/*"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
