name: Build macOS

on:
  push:
    branches: 
      - '*'

jobs:
  build:      
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Framework
        run: |
           set -o pipefail && xcodebuild -project TabBarUIAction.xcodeproj -scheme "TabBarUIAction" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=macOS,arch=x86_64" | xcpretty
      - name: Build Demo
        run: | 
           set -o pipefail && xcodebuild -project TabBarUIAction.xcodeproj -scheme "TabBarUIAction Demo" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=macOS,arch=x86_64" | xcpretty
      - name: Test
        run: |
           set -o pipefail && xcodebuild -project TabBarUIAction.xcodeproj -scheme "TabBarUIAction UITests" clean test -testPlan AllFeatures CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPad Air (4th generation),OS=latest' | xcpretty
